/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as IjtagRouteImport } from './routes/ijtag'
import { Route as DftRouteImport } from './routes/dft'
import { Route as IndexRouteImport } from './routes/index'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const IjtagRoute = IjtagRouteImport.update({
  id: '/ijtag',
  path: '/ijtag',
  getParentRoute: () => rootRouteImport,
} as any)
const DftRoute = DftRouteImport.update({
  id: '/dft',
  path: '/dft',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dft': typeof DftRoute
  '/ijtag': typeof IjtagRoute
  '/scan': typeof ScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dft': typeof DftRoute
  '/ijtag': typeof IjtagRoute
  '/scan': typeof ScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dft': typeof DftRoute
  '/ijtag': typeof IjtagRoute
  '/scan': typeof ScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dft' | '/ijtag' | '/scan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dft' | '/ijtag' | '/scan'
  id: '__root__' | '/' | '/dft' | '/ijtag' | '/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DftRoute: typeof DftRoute
  IjtagRoute: typeof IjtagRoute
  ScanRoute: typeof ScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ijtag': {
      id: '/ijtag'
      path: '/ijtag'
      fullPath: '/ijtag'
      preLoaderRoute: typeof IjtagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dft': {
      id: '/dft'
      path: '/dft'
      fullPath: '/dft'
      preLoaderRoute: typeof DftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DftRoute: DftRoute,
  IjtagRoute: IjtagRoute,
  ScanRoute: ScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
